language: java

dist: trusty

jdk:
  - oraclejdk8
  - openjdk8

script: ./scripts/build.sh

install: true
sudo: false

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: revamp
    jdk: openjdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2
