language: java
notifications:
  email: false
  hipchat:
    rooms:
      secure: Yw7l3qr8ymHAXAFujkjbC8TKBYxMXZF9eWSgbAr4kJLMCL6GXcWYbVL6gcYcPXgBJyeUzcAoy+XSmU+F+jUv5aNN19171kKaJaTyFi8OAxjxSqyqwnlqhmYMzo7gMKnOiuLzQVuE8OBd3kizBKyvMFsrhTjA+iYYc5fPG20XrY8=
install: true
script:
- mvn clean install
matrix:
  include:
  - jdk: openjdk7
