language: java

dist: trusty

jdk:
  - oraclejdk8
  - openjdk8

before_install:
  - git clone -b travis `git config --get remote.origin.url` travis

script: ./scripts/build.sh

install: true
sudo: false

cache:
  directories:
  - .autoconf
  - $HOME/.m2
