language: java

matrix:
  include:
  - jdk: oraclejdk8

install: true

sudo: false

cache:
  directories:
  - .autoconf
  - $HOME/.gradle

after_success:
  - ./gradlew clean build jar jacocoTestReport uploadArchives
  - bash <(curl -s https://codecov.io/bash)
